// Generated by gencpp from file haptics_parameters/Button.msg
// DO NOT EDIT!


#ifndef HAPTICS_PARAMETERS_MESSAGE_BUTTON_H
#define HAPTICS_PARAMETERS_MESSAGE_BUTTON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace haptics_parameters
{
template <class ContainerAllocator>
struct Button_
{
  typedef Button_<ContainerAllocator> Type;

  Button_()
    : A(0.0)
    , B(0.0)  {
    }
  Button_(const ContainerAllocator& _alloc)
    : A(0.0)
    , B(0.0)  {
  (void)_alloc;
    }



   typedef double _A_type;
  _A_type A;

   typedef double _B_type;
  _B_type B;





  typedef boost::shared_ptr< ::haptics_parameters::Button_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::haptics_parameters::Button_<ContainerAllocator> const> ConstPtr;

}; // struct Button_

typedef ::haptics_parameters::Button_<std::allocator<void> > Button;

typedef boost::shared_ptr< ::haptics_parameters::Button > ButtonPtr;
typedef boost::shared_ptr< ::haptics_parameters::Button const> ButtonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::haptics_parameters::Button_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::haptics_parameters::Button_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace haptics_parameters

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'haptics_parameters': ['/home/lab/telelocomotion_ws/src/haptics_parameters/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::haptics_parameters::Button_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::haptics_parameters::Button_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::haptics_parameters::Button_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::haptics_parameters::Button_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::haptics_parameters::Button_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::haptics_parameters::Button_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::haptics_parameters::Button_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ef19c74da855773d3bf3fef3bd6f069";
  }

  static const char* value(const ::haptics_parameters::Button_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ef19c74da855773ULL;
  static const uint64_t static_value2 = 0xd3bf3fef3bd6f069ULL;
};

template<class ContainerAllocator>
struct DataType< ::haptics_parameters::Button_<ContainerAllocator> >
{
  static const char* value()
  {
    return "haptics_parameters/Button";
  }

  static const char* value(const ::haptics_parameters::Button_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::haptics_parameters::Button_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 A\n\
float64 B\n\
";
  }

  static const char* value(const ::haptics_parameters::Button_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::haptics_parameters::Button_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.A);
      stream.next(m.B);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Button_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::haptics_parameters::Button_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::haptics_parameters::Button_<ContainerAllocator>& v)
  {
    s << indent << "A: ";
    Printer<double>::stream(s, indent + "  ", v.A);
    s << indent << "B: ";
    Printer<double>::stream(s, indent + "  ", v.B);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAPTICS_PARAMETERS_MESSAGE_BUTTON_H
