// Generated by gencpp from file haptics_parameters/Rotation.msg
// DO NOT EDIT!


#ifndef HAPTICS_PARAMETERS_MESSAGE_ROTATION_H
#define HAPTICS_PARAMETERS_MESSAGE_ROTATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace haptics_parameters
{
template <class ContainerAllocator>
struct Rotation_
{
  typedef Rotation_<ContainerAllocator> Type;

  Rotation_()
    : m00(0.0)
    , m01(0.0)
    , m02(0.0)
    , m10(0.0)
    , m11(0.0)
    , m12(0.0)
    , m20(0.0)
    , m21(0.0)
    , m22(0.0)  {
    }
  Rotation_(const ContainerAllocator& _alloc)
    : m00(0.0)
    , m01(0.0)
    , m02(0.0)
    , m10(0.0)
    , m11(0.0)
    , m12(0.0)
    , m20(0.0)
    , m21(0.0)
    , m22(0.0)  {
  (void)_alloc;
    }



   typedef double _m00_type;
  _m00_type m00;

   typedef double _m01_type;
  _m01_type m01;

   typedef double _m02_type;
  _m02_type m02;

   typedef double _m10_type;
  _m10_type m10;

   typedef double _m11_type;
  _m11_type m11;

   typedef double _m12_type;
  _m12_type m12;

   typedef double _m20_type;
  _m20_type m20;

   typedef double _m21_type;
  _m21_type m21;

   typedef double _m22_type;
  _m22_type m22;





  typedef boost::shared_ptr< ::haptics_parameters::Rotation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::haptics_parameters::Rotation_<ContainerAllocator> const> ConstPtr;

}; // struct Rotation_

typedef ::haptics_parameters::Rotation_<std::allocator<void> > Rotation;

typedef boost::shared_ptr< ::haptics_parameters::Rotation > RotationPtr;
typedef boost::shared_ptr< ::haptics_parameters::Rotation const> RotationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::haptics_parameters::Rotation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::haptics_parameters::Rotation_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace haptics_parameters

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'haptics_parameters': ['/home/lab/telelocomotion_ws/src/haptics_parameters/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::haptics_parameters::Rotation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::haptics_parameters::Rotation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::haptics_parameters::Rotation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::haptics_parameters::Rotation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::haptics_parameters::Rotation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::haptics_parameters::Rotation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::haptics_parameters::Rotation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c49cdc76b12ca71c6835d0870e0b24dd";
  }

  static const char* value(const ::haptics_parameters::Rotation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc49cdc76b12ca71cULL;
  static const uint64_t static_value2 = 0x6835d0870e0b24ddULL;
};

template<class ContainerAllocator>
struct DataType< ::haptics_parameters::Rotation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "haptics_parameters/Rotation";
  }

  static const char* value(const ::haptics_parameters::Rotation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::haptics_parameters::Rotation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 m00\n\
float64 m01\n\
float64 m02\n\
float64 m10\n\
float64 m11\n\
float64 m12\n\
float64 m20\n\
float64 m21\n\
float64 m22\n\
";
  }

  static const char* value(const ::haptics_parameters::Rotation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::haptics_parameters::Rotation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.m00);
      stream.next(m.m01);
      stream.next(m.m02);
      stream.next(m.m10);
      stream.next(m.m11);
      stream.next(m.m12);
      stream.next(m.m20);
      stream.next(m.m21);
      stream.next(m.m22);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Rotation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::haptics_parameters::Rotation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::haptics_parameters::Rotation_<ContainerAllocator>& v)
  {
    s << indent << "m00: ";
    Printer<double>::stream(s, indent + "  ", v.m00);
    s << indent << "m01: ";
    Printer<double>::stream(s, indent + "  ", v.m01);
    s << indent << "m02: ";
    Printer<double>::stream(s, indent + "  ", v.m02);
    s << indent << "m10: ";
    Printer<double>::stream(s, indent + "  ", v.m10);
    s << indent << "m11: ";
    Printer<double>::stream(s, indent + "  ", v.m11);
    s << indent << "m12: ";
    Printer<double>::stream(s, indent + "  ", v.m12);
    s << indent << "m20: ";
    Printer<double>::stream(s, indent + "  ", v.m20);
    s << indent << "m21: ";
    Printer<double>::stream(s, indent + "  ", v.m21);
    s << indent << "m22: ";
    Printer<double>::stream(s, indent + "  ", v.m22);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAPTICS_PARAMETERS_MESSAGE_ROTATION_H
